default: &default
  adapter: postgresql
  encoding: unicode
  username: d2ndjim
  password: postgres

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ecomm_development

test:
  <<: *default
  database: ecomm_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
